### PR TITLE
add datapoints for temperature as returned in the [ip]/temp call

### PR DESCRIPTION
**Pull request by hhindriks**
Dear rgwch

my wifi switch makes the temperature available as well, I think it is a newer revision. I added 3 data points for the measured, compensation and compensated temperature as returned in the call. I have not increased the version number or any other meta data.

Is it planned to make this adapter available in ioBroker by default?

thanks for the initial development, kind regards, Hajo

### CODE REVIEW

**Comment by rgwch** [comment]
Thanks a lot!  I took the opportunity to advance the version number to 1.0.0
regards, Gerry

**Comment by rgwch** [comment]
@hhindriks Hm, there's one Problem: With my (older) Mystrom Switches, there's an error: 
`by controller[0]: SyntaxError: Unexpected token < in JSON at position 0` Probably it's necessery to handle the answer of Switch correctly which doesn't know the new API call.

**Comment by hhindriks** [comment]
OK, this was my first javascript code. I didn't see a call to distinguish between the different revisions, so I am going to wrap the call with try..except. Maybe we can add a checkbox or drop down to the configuration?

**Comment by hhindriks** [comment]
Hi Gerry, wrapped the call in try..except to catch an error. Will be looking to either get the version information from the wifi switch or add a config option.

**Comment by rgwch** [comment]
oops I did the same thing just now, didn't see your post :-) It works here, but its not really elegant. I would prefer a config option.

**Comment by rgwch** [comment]
Yes, something like that. Can you make a new pull request for this?
Thanks!

**Pull request merged**
